import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Breadcrumbs from "@/components/breadcrumbs";
import { Toaster } from "@/components/ui/toaster";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || "https://localhost:8000"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Administrador E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="min-h-screen max-h-screen flex overflow-hidden">
        <Sidebar />
        <main className="flex-1 flex flex-col p-8 overflow-hidden">
          <Breadcrumbs />
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
