name: Deploy Applications

on:
  push:
    branches:
      - master  # Or your production branch

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy backend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_BACKEND_HOST }} << 'EOF'
            cd ECommerceVillaizan/
            git pull origin master
            cd backendecommerce/ 
            yarn 
            yarn build
            pm2 restart medusa
          EOF

  deploy-frontend:
    name: Deploy Frontends
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Ecommerce and Admin Frontend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST }} << 'EOF'
            cd ECommerceVillaizan/
            git pull origin main
            cd frontend/ 
            yarn
            yarn build
            pm2 restart ecommerce
            cd ../adminfront/
            npm install
            npm run build
            pm2 restart admin
          EOF
