name: Deploy Applications

on:
  push:
    branches:
      - master  # Or your production branch

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Build & Deploy Backend
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.EC2_BACKEND_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/ECommerceVillaizan/
            git pull origin master
            cd backendecommerce/
            yarn
            yarn build
            pm2 restart medusa
          '

      - name: Build & Deploy Frontend
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.EC2_FRONTEND_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/ECommerceVillaizan/
            git pull origin main
            cd frontend/
            yarn
            yarn build
            pm2 restart ecommerce
            cd ../adminfront/
            yarn
            yarn build
            pm2 restart admin
          '